#ifndef U_PRINTER_HPP
#define U_PRINTER_HPP

#include "Api.hpp"

#include <string>
#include <cstdarg>
#include <stdexcept>

namespace U {

template<typename TPrinter>
struct IsPrinter {
    static constexpr bool value = false;
};
    
// TODO: Think how to get rid of crtp, it may interact badly with DLLs generated by MSVC.
// Its real purpose here is to allow define the template method (pattern) printf(const char*, ...).
template <typename TImpl>
class Printer {
public:
    int printf(const char *format, ...) {
        va_list va;
        va_start(va, format);
        int result = static_cast<TImpl*>(this)->vprintf(format, va);
        va_end(va);
        return result;
    }
};

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, char c) {
    p.putc(c);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, const char *str) {
    p.puts(str);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, const std::string &str) {
    p.puts(str);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, int i) {
    p.printf("%d", i);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, size_t s) {
    p.printf("%zu", s);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, double d) {
    p.printf("%g", d);
    return p;
}

template<typename TPrinter,
         typename std::enable_if<U::IsPrinter<TPrinter>::value, int>::type = 0>
TPrinter &operator<<(TPrinter &p, bool b) {
    if (b)
        p.puts("true");
    else
        p.puts("false");
    return p;
}

}

#endif
